# numpy_exercises
- convert to .py when finished

### a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [1]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#assigned the variable neg_a to given array with the negative numbers filtered to get negative numbers in array
neg_a = a[a < 0]
print(f'neg_a = {neg_a}')
print()

#used the len() function to find how many negative numbers are in the array
print(f'There are {len(neg_a)} negative numbers in the array.')

neg_a = [-2 -1 -6 -7]

There are 4 negative numbers in the array.


### 2. How many positive numbers are there?

In [2]:
#assigned the variable pos_a to given array with the positive numbers filtered to get positive numbers in array
pos_a = a[a > 0]
print(f'pos_a = {pos_a}')
print()

#used the len() function to find how many positive numbers are in the array
print(f'There are {len(pos_a)} positive numbers in the array.')

pos_a = [ 4 10 12 23  3]

There are 5 positive numbers in the array.


### 3. How many even positive numbers are there?

In [3]:
#assigned even_pos_a to given array, filtering the positive and even numbers using a boolean filter
even_pos_a = a[(a > 0) & (a % 2 == 0)]
print(f'even_pos_a = {even_pos_a}')
print()

#used the len() function to find how many even AND positive numbers are in the array
print(f'There are {even_pos_a} numbers that are even AND positive in the array.')

even_pos_a = [ 4 10 12]

There are [ 4 10 12] numbers that are even AND positive in the array.


### 4. If you were to add 3 to each data point, how many positive numbers would there be?
- why do you get 6 on the end? 0 + 3 != 6

In [4]:
#assigned add_3 to the array that adds 3 to each number in a
add_3 = a + 3
print(f' These are all of the positive values you get when you add 3 to a:{a}')
print(f' ---------------------------------------------------------> add 3:{add_3[add_3 > 0]}')

 These are all of the positive values you get when you add 3 to a:[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
 ---------------------------------------------------------> add 3:[ 7 13 15 26  1  2  3  3  3  6]


### 5. If you squared each number, what would the new mean and standard deviation be?

In [5]:
#to get the value of a^2
a_squ = a**2
print(f'a^2:{a_squ}')
print()

print(f'The mean for a^2 = {a_squ.mean()}')
print()
print(f'The std dev for a^2 = {a_squ.std()}')

a^2:[ 16 100 144 529   4   1   0   0   0  36   9  49]

The mean for a^2 = 74.0

The std dev for a^2 = 144.0243035046516


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [6]:
#used the .mean() method to find the mean of each object in array a
print(f'The mean of array a = {a.mean()}')
print()

#substracted a.mean() from each object in array a to center the array around 0
a_center = a - a.mean()
print(f'Centering array a around 0 will give us the new array a_center:') 
print(f'{a_center}')

The mean of array a = 3.0

Centering array a around 0 will give us the new array a_center:
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


### 7. Calculate the z-score for each data point. Recall that the z-score is given by:
# Z = (x − μ) / σ

In [7]:
#divided a_center (already subtracted mean of a from a value) by std dev of a to get the z score
a_zscores = a_center / a.std()

print(f'The z-score for each data point in a is:{a_zscore}')

NameError: name 'a_zscore' is not defined

### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.
(see link in exercises)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Setup 1

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [ ]:
sum_of_a = sum(a)
print(sum_of_a)

### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [ ]:
min_of_a = min(a)
print(min_of_a)

### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [ ]:
max_of_a = max(a)
print(max(a))

### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [ ]:
mean_of_a = a.mean()
print(mean_of_a)

### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [ ]:
import scipy.special

product_of_a = scipy.special.factorial(a)
print(product_of_a)

### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [ ]:
squares_of_a = a**2
print(squares_of_a)

### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [ ]:
odds_in_a = a[a % 2 != 0]
print(odds_in_a)

### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens

In [ ]:
evens_in_a = a[a % 2 == 0]
print(evens_in_a)

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
### b = 
    [
    [3, 4, 5],
    [6, 7, 8]

# Setup 2

In [9]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [15]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
    
b = np.array(b)
[f'Sum: {b.sum()}, Min: {b.min()}, Max: {b.max()}, Avg: {b.mean()}, Product: {b.prod()}, Square: {b**2}']

['Sum: 33, Min: 3, Max: 8, Avg: 5.5, Product: 20160, Square: [[ 9 16 25]\n [36 49 64]]']

In [16]:
b

array([[3, 4, 5],
       [6, 7, 8]])

In [18]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
#numpy way

b[b % 2 != 0]

array([3, 5, 7])

In [20]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
#numpy way

b[b % 2 == 0]

array([4, 6, 8])

In [23]:
# Exercise 9 - print out the shape of the array b.

print(b.shape)

(2, 3)


In [25]:
# Exercise 10 - transpose the array b.

b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

In [27]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [29]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Setup 3

In [31]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

c = np.array(c)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
# Exercise 1 - Find the min, max, sum, and product of c.

print(f'Min: {c.min()}, Max: {c.max()}, Sum: {c.sum()}, Product: {c.prod()}')
print()

# Exercise 2 - Determine the standard deviation of c.
print(f'Std: {c.std()}')
print()

# Exercise 3 - Determine the variance of c.
print(f'Variance: {c.var()}')
print()

# Exercise 4 - Print out the shape of the array c
print(f'Shape: {c.shape}')
print()

# Exercise 5 - Transpose c and print out transposed result.
print(f'Transposed: \n{c.T}')
print()

# Exercise 6 - Get the dot product of the array c with c. 
print(f'Dot Product: \n{np.dot(c, c)}')
print()

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
print(f'c times c, transposed-sum: {(c * c.T).sum()}')
print()

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
print(f'c times c, transposed-product: {(c * c.T).prod()}')
print()


Min: 1, Max: 9, Sum: 45, Product: 362880

Std: 2.581988897471611

Variance: 6.666666666666667

Shape: (3, 3)

Transposed: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Dot Product: 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

c times c, transposed-sum: 261

c times c, transposed-product: 131681894400



# Setup 4

In [60]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [70]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [71]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [72]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [74]:
# Exercise 4 - Find all the negative numbers in d

d[d < 0]

array([-90, -30, -45, -45])

In [75]:
# Exercise 5 - Find all the positive numbers in d

d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [82]:
# Exercise 6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [85]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [86]:
# Exercise 8 - Print out the shape of d.

d.shape

(3, 6)

In [87]:
# Exercise 9 - Transpose and then print out the shape of d.

d.T.shape

(6, 3)

In [88]:
# Exercise 10 - Reshape d into an array of 9 x 2

d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])