# numpy_lesson

- num = numerical
- py = python
- linear algebra library for Python
- iterable = an object that holds multiple data points that you can iterate through
- opposite of a scalar which is an object that holds only one data point
- you can turn any iterable into a numpy array
- numpy.array is a data type
- matrix is a 2D list, a list of lists

In [5]:
%%timeit #magic method that times and operation in a cell
[x **2 for x in range(1, 1_000_000)]

412 ms ± 9.64 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%%timeit #magic method that times and operation in a cell
np.arange(1, 1_000_000) **2

2.59 ms ± 53.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
#convert list  into numpy array by overwriting x variable
x = [1, 2, 3, 4, 5]
x = np.array(x)
x

type(x)

numpy.ndarray

In [9]:
#gives us the shape of a variable which tells us ...
x.shape

(5,)

In [11]:
x

array([1, 2, 3, 4, 5])

# Arrays of Booleans 
- Boolean Masking
- Array filtering
- Indexing

##### True/False (think of this as a light switch)

In [13]:
a = np.array([5, 6, 7, 8])
a

array([5, 6, 7, 8])

In [15]:
show_second_fourth = np.array([False, True, False, True])

In [19]:
# sytax for filtering an array
    #also called: boolean masking or indexing
# similar to SQL code: 
    #select a where a > 6
a[a > 6]

array([7, 8])

In [20]:
#can also use this sytax
a[show_second_fourth]

array([6, 8])

In [24]:
np.random.randint(1, 4, 4)

array([2, 3, 3, 2])