# numpy_exercises
- convert to .py when finished

### a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

### 1. How many negative numbers are there?

In [1]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#assigned the variable neg_a to given array with the negative numbers filtered to get negative numbers in array
neg_a = a[a < 0]
print(f'neg_a = {neg_a}')
print()

#used the len() function to find how many negative numbers are in the array
print(f'There are {len(neg_a)} negative numbers in the array.')

neg_a = [-2 -1 -6 -7]

There are 4 negative numbers in the array.


### 2. How many positive numbers are there?

In [2]:
#assigned the variable pos_a to given array with the positive numbers filtered to get positive numbers in array
pos_a = a[a > 0]
print(f'pos_a = {pos_a}')
print()

#used the len() function to find how many positive numbers are in the array
print(f'There are {len(pos_a)} positive numbers in the array.')

pos_a = [ 4 10 12 23  3]

There are 5 positive numbers in the array.


### 3. How many even positive numbers are there?

In [3]:
#assigned even_pos_a to given array, filtering the positive and even numbers using a boolean filter
even_pos_a = a[(a > 0) & (a % 2 == 0)]
print(f'even_pos_a = {even_pos_a}')
print()

#used the len() function to find how many even AND positive numbers are in the array
print(f'There are {even_pos_a} numbers that are even AND positive in the array.')

even_pos_a = [ 4 10 12]

There are [ 4 10 12] numbers that are even AND positive in the array.


### 4. If you were to add 3 to each data point, how many positive numbers would there be?

In [4]:
#assigned add_3 to the array that adds 3 to each number in a
add_3 = a + 3
print(f' This is what you get when you add 3 to a:{a}')
print(f' ---------------------------------> add 3:{add_3}')

 This is what you get when you add 3 to a:[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
 ---------------------------------> add 3:[ 7 13 15 26  1  2  3  3  3 -3  6 -4]


### 5. If you squared each number, what would the new mean and standard deviation be?

In [5]:
#to get the value of a^2
a_squ = a**2
print(f'a^2:{a_squ}')
print()

print(f'The mean for a^2 = {a_squ.mean()}')
print()
print(f'The std dev for a^2 = {a_squ.std()}')

a^2:[ 16 100 144 529   4   1   0   0   0  36   9  49]

The mean for a^2 = 74.0

The std dev for a^2 = 144.0243035046516


### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [6]:
#used the .mean() method to find the mean of each object in array a
print(f'The mean of array a = {a.mean()}')
print()

#substracted a.mean() from each object in array a to center the array around 0
a_center = a - a.mean()
print(f'Centering array a around 0 will give us the new array a_center:') 
print(f'{a_center}')

The mean of array a = 3.0

Centering array a around 0 will give us the new array a_center:
[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]


### 7. Calculate the z-score for each data point. Recall that the z-score is given by:
# Z = (x − μ) / σ

In [7]:
#divided a_center (already subtracted mean of a from a value) by std dev of a to get the z score
a_zscore = a_center / a.std()

print(f'The z-score for each data point in a is:{a_zscore}')

The z-score for each data point in a is:[ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.
(see link in exercises)

In [9]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [10]:
sum_of_a = sum(a)
print(sum_of_a)

55


### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [11]:
min_of_a = min(a)
print(min_of_a)

1


### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [12]:
max_of_a = max(a)
print(max(a))

10


### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [14]:
mean_of_a = a.mean()
print(mean_of_a)

5.5


### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [29]:
import scipy.special

product_of_a = scipy.special.factorial(a)
print(product_of_a)

[1.0000e+00 2.0000e+00 6.0000e+00 2.4000e+01 1.2000e+02 7.2000e+02
 5.0400e+03 4.0320e+04 3.6288e+05 3.6288e+06]


### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [34]:
squares_of_a = a**2
print(squares_of_a)

[  1   4   9  16  25  36  49  64  81 100]


### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [38]:
odds_in_a = a[a % 2 != 0]
print(odds_in_a)

[1 3 5 7 9]


### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens

In [39]:
evens_in_a = a[a % 2 == 0]
print(evens_in_a)

[ 2  4  6  8 10]


### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
### b = 
    [
    [3, 4, 5],
    [6, 7, 8]